### ISSUE TITLE
Upload rate is always zero

### ISSUE THREAD

**Issue by amingilani** [petemyron/speedtest#1]
Hi, my upload rate is always 0

The rest all works perfectly. Any ideas?

**Comment by amingilani** [comment]
nevermind, works out

**Comment by darrellenns** [comment]
@amingilani could you share the fix? I'm seeing the same the same thing.

**Comment by amingilani** [comment]
@dack I can't remember exactly what happened but I think my internet was terrible :p

**Comment by darrellenns** [comment]
Thanks @amingilani. It's not my internet connection in my case, and I get normal results from the regular web based speedtest.net test. Are you able to reopen this issue? If not, then I'll start a new one.

I also see this when I enable debug:
Took 2.436219268 seconds to upload 0 bytes in 8 threads

Test code which exhibits the problem:
```
#!/usr/bin/env ruby
require 'speedtest'
test = Speedtest::Test.new(
  download_runs: 4,
    upload_runs: 4,
    ping_runs: 4,
    download_sizes: [750, 1500],
    upload_sizes: [10000, 400000],
    debug: true
 )
results=test.run
puts results.inspect
```

**Comment by amingilani** [comment]
I'd recommend opening a new issue and referencing this one.
ᐧ
